package com.developer.faculty.model;

public enum Subject {
    OBJECT_ORIENTED_PROGRAMMING,
    SOFTWARE_ENGINEERING,
    DATABASE_MANAGEMENT_SYSTEM,
    WEB_TECHNOLOGIES,
    COMPUTER_ARCHITECTURE,
    OPERATING_SYSTEM,
    DESIGN_AND_ANALYSIS_OF_ALGORITHMS
}
